# Generated by Django 3.0 on 2019-12-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='follower_count',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, to='twitterusers.TwitterUser'),
        ),
    ]
