# Generated by Django 3.0 on 2019-12-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterusers', '0002_auto_20191229_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='tweet_count',
        ),
    ]
