# Generated by Django 3.0 on 2019-12-30 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Body'),
        ),
    ]
