# Generated by Django 3.0 on 2019-12-30 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20191230_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Body'),
        ),
    ]
